// Generated by CoffeeScript 1.6.2
(function() {
  var routeMvc;

  module.exports = function(app) {
    var checkAuth;

    checkAuth = function(req, res, next) {
      if (!req.session.authorized) {
        res.statusCode = 401;
        return res.render('401', 401);
      } else {
        return next();
      }
    };
    app.all('/private', checkAuth, function(req, res, next) {
      return routeMvc('private', 'index', req, res, next);
    });
    app.get('/', function(req, res, next) {
      return routeMvc('products', 'index', req, res, next);
    });
    app.get('/:controller', function(req, res, next) {
      return routeMvc(req.params.controller, 'index', req, res, next);
    });
    app.get('/:controller/:id', function(req, res, next) {
      return routeMvc(req.params.controller, 'get', req, res, next);
    });
    app.post('/:controller', function(req, res, next) {
      return routeMvc(req.params.controller, 'create', req, res, next);
    });
    app.put('/:controller/:id', function(req, res, next) {
      return routeMvc(req.params.controller, 'update', req, res, next);
    });
    app.del('/:controller/:id', function(req, res, next) {
      return routeMvc(req.params.controller, 'delete', req, res, next);
    });
    return app.all('/*', function(req, res) {
      console.warn("error 404: ", req.url);
      res.statusCode = 404;
      return res.render('404', 404);
    });
  };

  routeMvc = function(controllerName, methodName, req, res, next) {
    var controller, e;

    try {
      controller = require("./controllers/" + controllerName);
      return controller[methodName](req, res);
    } catch (_error) {
      e = _error;
      console.warn("controller not found: " + controllerName, e);
      next();
    }
  };

  /*
    controllerName = 'index' if not controllerName?
    controller = null
    try
    catch e
      console.warn "controller not found: " + controllerName, e
      next()
      return
    data = null
    if typeof controller[methodName] is 'function'
      actionMethod = controller[methodName].bind controller
      actionMethod req, res, next
    else
      console.warn 'method not found: ' + methodName
      next()
  */


}).call(this);
