// Generated by CoffeeScript 1.6.2
(function() {
  var Product, Products;

  Product = require('../models/product');

  Products = (function() {
    function Products() {}

    Products.prototype.index = function(req, res) {
      return Product.find({}, function(err, products) {
        return res.render('products', {
          'products': products
        });
      });
    };

    Products.prototype.get = function(req, res) {
      return Product.findById(req.params.id, function(err, product) {
        if (!err) {
          res.render('products/product', {
            'product': product
          });
          return res.statusCode = 200;
        } else {
          res.send(err);
          return res.statusCode = 500;
        }
      });
    };

    Products.prototype.create = function(req, res) {
      var product;

      product = new Product(req.body);
      return product.save(function(err, product) {
        if (!err) {
          res.send(product);
          return res.statusCode = 201;
        } else {
          res.send(err);
          return res.statusCode = 500;
        }
      });
    };

    Products.prototype.update = function(req, res) {
      return Product.findByIdAndUpdate(req.params.id, {
        "$set": req.body
      }, function(err, product) {
        if (!err) {
          res.send(product);
          return res.statusCode = 200;
        } else {
          res.send(err);
          return res.statusCode = 418;
        }
      });
    };

    Products.prototype["delete"] = function(req, res) {
      return Product.findByIdAndRemove(req.params.id, function(err) {
        if (!err) {
          return res.render('products', {
            'products': products
          });
        } else {
          res.send(err);
          return res.statusCode = 500;
        }
      });
    };

    return Products;

  })();

  module.exports = new Products;

}).call(this);
