// Generated by CoffeeScript 1.6.2
(function() {
  var Product;

  Product = require('../models/product');

  module.exports = {
    index: function(req, res) {
      return Product.find({}, function(err, products) {
        return res.render('products', {
          'products': products
        });
      });
    },
    get: function(req, res) {
      return Product.findById(req.params.id, function(err, product) {
        if (!err) {
          res.render('products/product', {
            'product': product
          });
          return res.statusCode = 200;
        } else {
          res.send(err);
          return res.statusCode = 500;
        }
      });
    },
    create: function(req, res) {
      var product;

      product = new Product(req.body);
      return product.save(function(err, product) {
        if (!err) {
          res.send(product);
          return res.statusCode = 201;
        } else {
          res.send(err);
          return res.statusCode = 500;
        }
      });
    },
    update: function(req, res) {
      return Product.findByIdAndUpdate(req.params.id, {
        "$set": req.body
      }, function(err, product) {
        if (!err) {
          res.send(product);
          return res.statusCode = 200;
        } else {
          res.send(err);
          return res.statusCode = 500;
        }
      });
    },
    "delete": function(req, res) {
      return Product.findByIdAndRemove(req.params.id, function(err) {
        if (!err) {
          return res.send({});
        } else {
          res.send(err);
          return res.statusCode = 500;
        }
      });
    }
  };

}).call(this);
