// Generated by CoffeeScript 1.6.2
(function() {
  var Product, mongoose;

  mongoose = require('mongoose');

  Product = new mongoose.Schema({
    name: {
      type: String,
      required: true,
      unique: true,
      index: true
    },
    description: String,
    price: Number
  });

  module.exports = mongoose.model('Product', Product);

}).call(this);
