// Generated by CoffeeScript 1.6.2
(function() {
  var User, mongoose;

  mongoose = require('mongoose');

  User = new mongoose.Schema({
    login: String,
    password: String,
    email: String
  });

  module.exports = mongoose.model('User', User);

}).call(this);
